"""
CrewAI Multi-Agent Coordinator
Runs multiple agents in parallel for efficient content generation and analysis
"""
from typing import List, Dict, Any
from crewai import Agent, Task, Crew, Process
from langchain_openai import ChatOpenAI

from backend.core.config import settings


class LearningAgentCrew:
    """
    CrewAI-based multi-agent system for parallel learning content operations
    """

    def __init__(self):
        # Initialize LLMs for different agents
        self.gpt4 = ChatOpenAI(
            model="gpt-4-turbo-preview",
            temperature=0.7,
            api_key=settings.OPENAI_API_KEY
        )

        self.gpt35 = ChatOpenAI(
            model="gpt-3.5-turbo",
            temperature=0.5,
            api_key=settings.OPENAI_API_KEY
        )

        # Create specialized agents
        self.content_researcher = self._create_content_researcher()
        self.problem_creator = self._create_problem_creator()
        self.explanation_writer = self._create_explanation_writer()
        self.progress_analyst = self._create_progress_analyst()

    def _create_content_researcher(self) -> Agent:
        """Agent specialized in finding and evaluating learning content"""
        return Agent(
            role='Content Research Specialist',
            goal='Find the most relevant, high-quality learning content for any topic',
            backstory="""You are an expert at finding educational content across the internet.
            You know how to identify high-quality tutorials, articles, videos, and documentation.
            You understand what makes content effective for different learning styles and skill levels.""",
            llm=self.gpt4,
            verbose=True,
            allow_delegation=False
        )

    def _create_problem_creator(self) -> Agent:
        """Agent specialized in creating practice problems"""
        return Agent(
            role='Practice Problem Designer',
            goal='Create engaging, educational practice problems that test understanding',
            backstory="""You are a master at creating practice problems that help students learn.
            Your problems are clear, practical, and progressively challenging.
            You understand pedagogy and how to reinforce learning through deliberate practice.""",
            llm=self.gpt4,
            verbose=True,
            allow_delegation=False
        )

    def _create_explanation_writer(self) -> Agent:
        """Agent specialized in writing clear explanations"""
        return Agent(
            role='Technical Explanation Writer',
            goal='Write crystal-clear explanations of complex technical concepts',
            backstory="""You are an expert technical writer who can explain anything clearly.
            You use analogies, examples, and progressive disclosure to make concepts accessible.
            You tailor your explanations to the learner's level.""",
            llm=self.gpt4,
            verbose=True,
            allow_delegation=False
        )

    def _create_progress_analyst(self) -> Agent:
        """Agent specialized in analyzing learning progress"""
        return Agent(
            role='Learning Progress Analyst',
            goal='Analyze learning data and provide actionable insights',
            backstory="""You are a data analyst specializing in educational metrics.
            You can identify patterns in learning behavior and suggest improvements.
            You understand spaced repetition, mastery learning, and cognitive load.""",
            llm=self.gpt35,
            verbose=True,
            allow_delegation=False
        )

    async def generate_comprehensive_session_content(
        self,
        topic: str,
        difficulty: str,
        duration_minutes: int,
        user_context: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Use CrewAI to generate all session content in parallel

        Args:
            topic: Learning topic
            difficulty: Difficulty level
            duration_minutes: Session duration
            user_context: User's learning context

        Returns:
            Complete session content generated by the crew
        """

        # Define tasks for each agent
        tasks = [
            Task(
                description=f"""
                Research and recommend the top 3 learning resources for:
                Topic: {topic}
                Difficulty: {difficulty}
                Duration available: {duration_minutes // 2} minutes for content review

                User context:
                {self._format_user_context(user_context)}

                Provide:
                1. Resource title and URL
                2. Why it's relevant
                3. Estimated time to complete
                4. Key concepts covered

                Focus on recent, highly-rated content that matches the user's level.
                """,
                agent=self.content_researcher,
                expected_output="List of 3 recommended learning resources with detailed justification"
            ),

            Task(
                description=f"""
                Create 5 practice problems for:
                Topic: {topic}
                Difficulty: {difficulty}

                User skill level: {user_context.get('skill_level', 50)}/100

                Create a mix of:
                - 2 multiple choice questions
                - 2 coding problems (if applicable)
                - 1 conceptual explanation question

                Each problem should:
                - Test a specific concept
                - Include clear instructions
                - Have hints for struggling learners
                - Include detailed solutions

                Make problems progressively challenging.
                """,
                agent=self.problem_creator,
                expected_output="5 well-structured practice problems with solutions and explanations"
            ),

            Task(
                description=f"""
                Write a clear, concise explanation of the key concepts in:
                Topic: {topic}
                Difficulty: {difficulty}

                This explanation will be shown at the start of the learning session.

                Requirements:
                - 200-300 words
                - Use simple language
                - Include 1-2 practical examples
                - Highlight why this topic matters
                - Connect to user's goals: {user_context.get('goals', [])}

                Make it engaging and motivating.
                """,
                agent=self.explanation_writer,
                expected_output="Engaging introduction explanation (200-300 words)"
            ),

            Task(
                description=f"""
                Analyze the user's learning progress and provide recommendations:

                User Context:
                {self._format_user_context(user_context)}

                Provide:
                1. Progress assessment (strengths and areas for improvement)
                2. Recommended focus areas for this session
                3. Suggested difficulty adjustments
                4. Motivation and encouragement

                Be specific and actionable.
                """,
                agent=self.progress_analyst,
                expected_output="Detailed progress analysis with specific recommendations"
            )
        ]

        # Create crew and run tasks in parallel
        crew = Crew(
            agents=[
                self.content_researcher,
                self.problem_creator,
                self.explanation_writer,
                self.progress_analyst
            ],
            tasks=tasks,
            process=Process.hierarchical,  # Parallel execution
            verbose=True
        )

        # Execute the crew
        result = crew.kickoff()

        # Parse and structure the results
        structured_result = self._parse_crew_results(result, tasks)

        return structured_result

    def _format_user_context(self, context: Dict[str, Any]) -> str:
        """Format user context for agent consumption"""
        return f"""
        - Skill Level: {context.get('skill_level', 'Unknown')}/100
        - Topics Studied: {', '.join(context.get('topics_studied', []))}
        - Learning Goals: {', '.join(context.get('goals', []))}
        - Recent Performance: {context.get('recent_accuracy', 'N/A')}%
        - Total Sessions: {context.get('total_sessions', 0)}
        - Current Streak: {context.get('streak', 0)} days
        """

    def _parse_crew_results(self, result: str, tasks: List[Task]) -> Dict[str, Any]:
        """Parse CrewAI results into structured format"""

        # CrewAI returns concatenated results, we need to parse them
        # In production, you'd have more sophisticated parsing

        return {
            "content_recommendations": {
                "raw_output": result,
                "message": "Content researched by AI crew"
            },
            "practice_problems": {
                "raw_output": result,
                "message": "Problems created by AI crew"
            },
            "introduction": {
                "raw_output": result,
                "message": "Introduction written by AI crew"
            },
            "progress_analysis": {
                "raw_output": result,
                "message": "Progress analyzed by AI crew"
            },
            "crew_execution_successful": True
        }

    async def evaluate_session_content(
        self,
        content_items: List[Dict[str, Any]],
        problems: List[Dict[str, Any]],
        topic: str,
        difficulty: str
    ) -> Dict[str, Any]:
        """
        Use agents to evaluate and improve generated content

        Args:
            content_items: List of content to evaluate
            problems: List of problems to evaluate
            topic: Topic
            difficulty: Difficulty level

        Returns:
            Evaluation and improvement suggestions
        """

        evaluation_task = Task(
            description=f"""
            Evaluate this learning session content for quality and effectiveness:

            Topic: {topic}
            Difficulty: {difficulty}

            Content Items ({len(content_items)}):
            {self._format_content_list(content_items)}

            Practice Problems ({len(problems)}):
            {self._format_problems_list(problems)}

            Evaluate:
            1. Content relevance and quality (1-10)
            2. Problem difficulty appropriateness (1-10)
            3. Coverage of key concepts (1-10)
            4. Engagement potential (1-10)
            5. Specific improvements suggested

            Provide scores and detailed feedback.
            """,
            agent=self.progress_analyst,
            expected_output="Quality evaluation with scores and improvement suggestions"
        )

        crew = Crew(
            agents=[self.progress_analyst],
            tasks=[evaluation_task],
            verbose=True
        )

        result = crew.kickoff()

        return {
            "evaluation": result,
            "timestamp": "now"
        }

    def _format_content_list(self, content: List[Dict[str, Any]]) -> str:
        """Format content list for display"""
        return "\n".join([
            f"- {item.get('title', 'Untitled')} ({item.get('type', 'unknown')})"
            for item in content
        ])

    def _format_problems_list(self, problems: List[Dict[str, Any]]) -> str:
        """Format problems list for display"""
        return "\n".join([
            f"- {i+1}. {prob.get('question', 'No question')[:50]}... ({prob.get('type', 'unknown')})"
            for i, prob in enumerate(problems)
        ])


# Example usage function
async def create_parallel_session_content(
    topic: str,
    difficulty: str,
    duration: int,
    user_data: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Helper function to create session content using CrewAI

    This demonstrates how to use the crew for efficient parallel generation
    """

    crew_coordinator = LearningAgentCrew()

    result = await crew_coordinator.generate_comprehensive_session_content(
        topic=topic,
        difficulty=difficulty,
        duration_minutes=duration,
        user_context=user_data
    )

    return result
